scrape_configs:
  - job_name: "alluxio master"
    metrics_path: '/metrics/prometheus/'
    static_configs:
      - targets: [ 'ec2-18-206-255-136.compute-1.amazonaws.com:19999' ]
  - job_name: "alluxio worker-0"
    metrics_path: '/metrics/prometheus/'
    static_configs:
      - targets: [ 'ec2-3-95-137-4.compute-1.amazonaws.com:30000' ]
  - job_name: "alluxio worker-1"
    metrics_path: '/metrics/prometheus/'
    static_configs:
      - targets: [ 'ec2-44-206-241-60.compute-1.amazonaws.com:30000' ]
  - job_name: "alluxio worker-2"
    metrics_path: '/metrics/prometheus/'
    static_configs:
      - targets: [ 'ec2-54-197-196-140.compute-1.amazonaws.com:30000' ]
  - job_name: "alluxio worker-3"
    metrics_path: '/metrics/prometheus/'
    static_configs:
      - targets: [ 'ec2-54-227-9-74.compute-1.amazonaws.com:30000' ]
  - job_name: "alluxio job master"
    metrics_path: '/metrics/prometheus/'
    static_configs:
      - targets: [ 'ec2-18-206-255-136.compute-1.amazonaws.com:20002' ]

  - job_name: "alluxio job worker-0"
    metrics_path: '/metrics/prometheus/'
    static_configs:
      - targets: [ 'ec2-3-95-137-4.compute-1.amazonaws.com:30003' ]
