{
 "title": "Alluxio-Prometheus-Grafana-Monitor Copy",
 "time": { "from": "now-2d", "to": "2023-08-02T13:30:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "alluxio_datasource",
    "label": "The datasource of alluxio prometheus",
    "query": "prometheus"
   },
   {
    "name": "masters",
    "label": "The prometheus job_name including master nodes",
    "query": "alluxio master"
   },
   {
    "name": "workers",
    "label": "The prometheus job_name including worker nodes",
    "query": "alluxio worker"
   },
   { "name": "alluxio_user", "label": "The super user of alluxio", "query": "alluxio" }
  ]
 },
 "panels": [
  {
   "title": "active_client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "Worker_ActiveClients_Ec2Cluster_workers_0",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_ActiveClients_Ec2Cluster_workers_1",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_ActiveClients_Ec2Cluster_workers_2",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_ActiveClients_Ec2Cluster_workers_3",
     "legendFormat": "__auto"
    },
    { "expression": "($A+$B+$C+$D)", "type": "math" }
   ]
  },
  {
   "title": "readUFS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "Worker_BytesReadPerUfs_UFS:s3:_2F_2Falluxio_tpch100_2FcacheTest_50MB_User:_Ec2Cluster_workers_0/1024/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BytesReadPerUfs_UFS:s3:_2F_2Falluxio_tpch100_2FcacheTest_50MB_User:_Ec2Cluster_workers_1/1024/1024/1024\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BytesReadPerUfs_UFS:s3:_2F_2Falluxio_tpch100_2FcacheTest_50MB_User:_Ec2Cluster_workers_2/1024/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BytesReadPerUfs_UFS:s3:_2F_2Falluxio_tpch100_2FcacheTest_50MB_User:_Ec2Cluster_workers_3/1024/1024/1024",
     "legendFormat": "__auto"
    },
    { "expression": "($A+$B+$C+$D)", "type": "math" }
   ]
  },
  {
   "title": "block read UFS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "Worker_BlocksReadUfs_Ec2Cluster_workers_0",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksReadUfs_Ec2Cluster_workers_1",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksReadUfs_Ec2Cluster_workers_2",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksReadUfs_Ec2Cluster_workers_3",
     "legendFormat": "__auto"
    },
    { "expression": "($A+$B+$C+$D)", "type": "math" }
   ]
  },
  {
   "title": "Worker_remoteRead",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "Worker_BytesReadRemote_Ec2Cluster_workers_0/1024/1024/1024\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BytesReadRemote_Ec2Cluster_workers_1/1024/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BytesReadRemote_Ec2Cluster_workers_2/1024/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BytesReadRemote_Ec2Cluster_workers_3/1024/1024/1024",
     "legendFormat": "__auto"
    },
    { "expression": "($A+$B+$C+$D)", "type": "math" }
   ]
  },
  {
   "title": "block_readLocal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "Worker_BlocksReadLocal_Ec2Cluster_workers_0",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksReadLocal_Ec2Cluster_workers_1",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksReadLocal_Ec2Cluster_workers_2",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksReadLocal_Ec2Cluster_workers_3",
     "legendFormat": "__auto"
    },
    { "expression": "($A+$B+$C+$D)", "type": "math" }
   ]
  },
  {
   "title": "block read remote",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "Worker_BlocksReadRemote_Ec2Cluster_workers_0",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksReadRemote_Ec2Cluster_workers_1",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksReadRemote_Ec2Cluster_workers_2",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksReadRemote_Ec2Cluster_workers_3",
     "legendFormat": "__auto"
    },
    { "expression": "($A+$B+$C+$D)", "type": "math" }
   ]
  },
  {
   "title": "Block_Accessed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "Worker_BlocksAccessed_Ec2Cluster_workers_0\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksAccessed_Ec2Cluster_workers_1",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksAccessed_Ec2Cluster_workers_2",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksAccessed_Ec2Cluster_workers_3",
     "legendFormat": "__auto"
    },
    { "expression": "($A+$B+$C+$D)", "type": "math" }
   ]
  },
  {
   "title": "Cache_Remote",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "Worker_CacheRemoteBlocks_Ec2Cluster_workers_0",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_CacheRemoteBlocks_Ec2Cluster_workers_1",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_CacheRemoteBlocks_Ec2Cluster_workers_2",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_CacheRemoteBlocks_Ec2Cluster_workers_3",
     "legendFormat": "__auto"
    },
    { "expression": "($A+$B+$C+$D)", "type": "math" }
   ]
  },
  {
   "title": "Worker_BlockEvict",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "Worker_BlocksEvicted_Ec2Cluster_workers_0",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksEvicted_Ec2Cluster_workers_1",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksEvicted_Ec2Cluster_workers_2",
     "legendFormat": "__auto"
    },
    {
     "expr": "Worker_BlocksEvicted_Ec2Cluster_workers_3",
     "legendFormat": "__auto"
    },
    { "expression": "($A+$B+$C+$D)", "type": "math" }
   ]
  },
  {
   "title": "Alluxio IO Key Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes Read Local (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(Cluster_BytesReadLocal{job=\"$masters\"}[1m])",
     "legendFormat": "Bytes Read Local (Per Minute)"
    }
   ]
  },
  {
   "title": "Bytes Read Remote (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(Cluster_BytesReadRemote{job=\"$masters\"}[1m])",
     "legendFormat": "Bytes Read Remote (Per Minute)"
    }
   ]
  },
  {
   "title": "Bytes Read UFS (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(Cluster_BytesReadUfsAll{job=\"$masters\"}[1m])",
     "legendFormat": "Bytes Read UFS (Per Minute)"
    }
   ]
  },
  {
   "title": "Live Workers",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Cluster_Workers{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Bytes Read Local",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_BytesReadLocal{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Bytes Read Remote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_BytesReadRemote{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "% Alluxio Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(Cluster_CapacityUsed{job=\"$masters\"}) / Cluster_CapacityTotal{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "% Worker Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"Worker_CapacityUsed_.*\",job=\"$workers\"}/{__name__=~\"Worker_CapacityTotal_.*\",job=\"$workers\"}"
    }
   ]
  },
  {
   "title": "% UFS Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "Cluster_RootUfsCapacityUsed{job=\"$masters\"}/Cluster_RootUfsCapacityTotal{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Alluxio Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_CapacityTotal{job=\"$masters\"}"
    },
    {
     "expr": "Cluster_CapacityUsed{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Worker Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"Worker_CapacityTotal_.*\",job=\"$workers\"}"
    },
    {
     "expr": "{__name__=~\"Worker_CapacityUsed_.*\",job=\"$workers\"}"
    }
   ]
  },
  {
   "title": "UFS Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_RootUfsCapacityTotal{job=\"$masters\"}"
    },
    {
     "expr": "Cluster_RootUfsCapacityUsed{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Workers Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cached Blocks ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlocksCached.*\",job=\"$workers\"}"
    }
   ]
  },
  {
   "title": "Deleted Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlocksDeleted.*\",job=\"$workers\"}"
    }
   ]
  },
  {
   "title": "Lost Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlocksLost.*\",job=\"$workers\"}"
    }
   ]
  },
  {
   "title": "Evicted Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"Worker_BlocksEvicted.*\",job=\"$workers\"}"
    }
   ]
  },
  {
   "title": "Logical Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Directories Created",
   "type": "stat",
   "description": "Displays the current number of how many directories Alluxio has created since starting",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_DirectoriesCreated{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "File Infos Got",
   "type": "stat",
   "description": "displays the number of times the FileInfosGot operation was called",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_FileInfosGot{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Total Paths",
   "type": "stat",
   "description": "Displays the total paths located in the Alluxio file system",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_TotalPaths{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Complete File Operations",
   "type": "stat",
   "description": "Displays how many times the CompleteFile operation has been called",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_CompleteFileOps{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Create Directory Oprtations",
   "type": "stat",
   "description": "Displays the amount of directories that Alluxio has created (Not the current amount of directories)",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_CreateDirectoryOps{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Delete Path Operations",
   "type": "stat",
   "description": "Displays how many times the deletePath operation has been called (And how many total paths have been deleted)",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_DeletePathOps{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Files Pinned",
   "type": "stat",
   "description": "Displays the current number of pinned files in Alluxio",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_FilesPinned{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Mount Operations",
   "type": "stat",
   "description": "Displays how many times the mount operation has been called (including failed invocations)",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_MountOps{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Files Freed",
   "type": "stat",
   "description": "Displays the current number of freed files in Alluxio",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_FilesFreed{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Unmount Operations",
   "type": "stat",
   "description": "Displays how many times the unmount operation has been called",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Master_UnmountOps{job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Alluxio Metadata Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GetStatus Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_GetStatus_User:$alluxio_user\",job=\"$masters\",quantile=\"0.5\"}"
    },
    {
     "expr": "{__name__=\"Master_GetStatus_User:$alluxio_user\",job=\"$masters\",quantile=\"0.95\"}"
    },
    {
     "expr": "{__name__=\"Master_GetStatus_User:$alluxio_user\",job=\"$masters\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "ListStatus Operation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 97 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_ListStatus_User:$alluxio_user\",job=\"$masters\",quantile=\"0.5\"}"
    },
    {
     "expr": "{__name__=\"Master_ListStatus_User:$alluxio_user\",job=\"$masters\",quantile=\"0.95\"}"
    },
    {
     "expr": "{__name__=\"Master_ListStatus_User:$alluxio_user\",job=\"$masters\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "Get Configuration Operation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 97 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_getConfiguration\",job=\"$masters\",quantile=\"0.5\"}"
    },
    {
     "expr": "{__name__=\"Master_getConfiguration\",job=\"$masters\",quantile=\"0.95\"}"
    },
    {
     "expr": "{__name__=\"Master_getConfiguration\",job=\"$masters\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "Block Heartbeat Operation",
   "type": "graph",
   "description": "Displays the 50th, 95th, and 99th percentiles call time for the blockHeartbeat metadata operation.\n\nNote: This is not a graph for the actual Block Heartbeat just how long it took the operation to run",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_blockHeartbeat_User:$alluxio_user\",job=\"$masters\",quantile=\"0.5\"}"
    },
    {
     "expr": "{__name__=\"Master_blockHeartbeat_User:$alluxio_user\",job=\"$masters\",quantile=\"0.95\"}"
    },
    {
     "expr": "{__name__=\"Master_blockHeartbeat_User:$alluxio_user\",job=\"$masters\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "Worker Heartbeat Operation",
   "type": "graph",
   "description": "Displays the 50th, 95th, and 99th percentiles call time for the workerHeartbeat metadata operation.\n\nNote: This is not a graph for the actual Worker Heartbeat just how long it took the operation to run",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"Worker_Heartbeat_User:$alluxio_user[a-zA-Z0-9_]+\",job=\"$workers\",quantile=\"0.5\"}"
    },
    {
     "expr": "{__name__=~\"Worker_Heartbeat_User:$alluxio_user[a-zA-Z0-9_]+\",job=\"$workers\",quantile=\"0.95\"}"
    },
    {
     "expr": "{__name__=~\"Worker_Heartbeat_User:$alluxio_user[a-zA-Z0-9_]+\",job=\"$workers\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "AsyncCache Blocks & Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {}
   ]
  },
  {
   "title": "AsyncCacheSuccessedBlocks (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase({__name__=~\"Worker_AsyncCacheSucceededBlocks.*\",job=\"$workers\"}[1m])"
    }
   ]
  },
  {
   "title": "AsyncCacheFailedBlocks (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase({__name__=~\"Worker_AsyncCacheFailedBlocks.*\",job=\"$workers\"}[1m])"
    }
   ]
  },
  {
   "title": "AsyncCacheRemoteBlocks (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase({__name__=~\"Worker_AsyncCacheRemoteBlocks.*\",job=\"$workers\"}[1m])"
    }
   ]
  },
  {
   "title": "AsyncCacheUfsBlocks (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase({__name__=~\"Worker_AsyncCacheUfsBlocks.*\",job=\"$workers\"}[1m])"
    }
   ]
  },
  {
   "title": "AsyncCacheRequests (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase({__name__=~\"Worker_AsyncCacheRequests.*\",job=\"$workers\"}[1m])"
    }
   ]
  },
  {
   "title": "AsyncCacheDuplicateRequests (Per Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase({__name__=~\"Worker_AsyncCacheDuplicateRequests.*\",job=\"$workers\"}[1m])"
    }
   ]
  },
  {
   "title": "Master JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Master Pools Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"pools_Compressed_Class_Space_used\", job=\"$masters\"}"
    },
    {
     "expr": "{__name__=\"pools_Metaspace_used\", job=\"$masters\"}"
    },
    {
     "expr": "{__name__=\"pools_PS_Eden_Space_used\", job=\"$masters\"}"
    },
    {
     "expr": "{__name__=\"pools_PS_Survivor_Space_used\", job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Master Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 120 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"heap_used\",job=\"$masters\"}"
    },
    {
     "expr": "{__name__=\"heap_max\",job=\"$masters\"}"
    },
    {
     "expr": "{__name__=\"non_heap_used\",job=\"$masters\"}"
    }
   ]
  },
  {
   "title": "Master Total Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 120 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"total_max\",job=\"$masters\"}"
    },
    {
     "expr": "{__name__=\"total_used\",job=\"$masters\"}"
    }
   ]
  }
 ]
}